const NPO_Animals = [
  {
    id: 1,
    name: "Animal_welfare_name_string",
    Address: "Adsress_string",
    Telephone: 123456789,
    Website: "link",
    image_url: "",
    Fcaebook: "",
    Instagram: "",
  },
  {
    id: 1,
    name: "Animal_welfare_name_string",
    Address: "Adsress_string",
    Telephone: 123456789,
    Website: "link",
    image_url: "",
    Fcaebook: "",
    Instagram: "",
  },
  {
    id: 1,
    name: "Animal_welfare_name_string",
    Address: "Adsress_string",
    Telephone: 123456789,
    Website: "link",
    image_url: "",
    Fcaebook: "",
    Instagram: "",
  },
  {
    id: 1,
    name: "Animal_welfare_name_string",
    Address: "Adsress_string",
    Telephone: 123456789,
    Website: "link",
    image_url: "",
    Fcaebook: "",
    Instagram: "",
  },
  {
    id: 1,
    name: "Animal_welfare_name_string",
    Address: "Adsress_string",
    Telephone: 123456789,
    Website: "link",
    image_url: "",
    Fcaebook: "",
    Instagram: "",
  },
];
